[package]

name = "mod_example"
version = "0.0.2"

[lib]
name = "mod_example"
crate-type = ["dylib"]

[dependencies]
wagi = { git = "https://github.com/deislabs/wagi" }
apache-rs = { git = "https://github.com/studersi/apache-rs" }
